Fix imports in cannonfile
The current example file produces the error:

```
TypeError: Cannot read properties of undefined (reading 'CoreProxy')
```

This updates the import paths so that the addresses can be retrieved.